### ISSUE TITLE
Date-time confusion

### ISSUE THREAD

**Issue by ArthurClemens** [miracle2k/tarsnapper#14]
I have a bunch of test files, named like this:

```
test-20141025-163600.txt
test-20141025-164600.txt
test-20141025-165600.txt
test-20141025-170600.txt
```

This is my job configuration:

```
  test-txt:
    source: /home/backup/
    alias: test
    target: test-$date.txt
    deltas: 1h 1d 3d
```

I would expect that this reads the filename "test-" + date `20141025-163600` + ".txt". But when calling make I get:

```
Creating backup test-txt: test-20141025-204440.txt
```

It discards the time value in the file name and inserts the current time of the machine. It also creates only 1 backup file. This seems like a bug to me.
