### ISSUE TITLE
Strange behavior of expiration

### ISSUE THREAD

**Issue by estan** [miracle2k/tarsnapper#15]
Hi,

I'm in the process of setting up tarsnap + tarsnapper on my FreeBSD server.

I currently have the following small tarsnapper.conf:

```
deltas: 1d 7d 30d
target: $name-$date

jobs:
  backup:
    sources:
      - /etc
      - /usr/local/etc
```

I tried to create a couple of backups by invoking `tarsnapper -c /usr/local/etc/tarsnapper.conf make`. But then I encountered this behavior:

```
root@www:/etc/periodic/daily # tarsnap --list-archives
backup-20141026-181732
backup-20141026-174741
root@www:/etc/periodic/daily # tarsnap -c /usr/local/etc/tarsnapper.conf make
Creating backup backup: backup-20141026-182234
3 backups are matching
1 of those can be deleted
Deleting backup-20141026-181732
root@www:/etc/periodic/daily # tarsnap --list-archives
backup-20141026-182234
backup-20141026-174741
```

Why did it remove the backup-20141026-181732 archive?

(These commands were all run today while I was testing).
