### ISSUE TITLE
Can i specify a directory as a source for a job?

### ISSUE THREAD

**Issue by coaxial** [miracle2k/tarsnapper#48]
Say I want to backup everything under `/etc/`, can I have a job like this?

```
jobs:
  whynot:
    sources:
      - /etc
```

It is not clear to me from the readme.
